# Generated by Django 2.2.7 on 2019-11-27 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protected', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualDevice',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('state_on_action', models.CharField(choices=[('nothing', 'Do Nothing'), ('chime', 'Play Default Chime'), ('siren', 'Play Siren'), ('custom', 'Play custom sound')], default='nothing', max_length=8)),
                ('state', models.CharField(choices=[('off', 'Off'), ('chime', 'Chime'), ('chime', 'Siren Alert')], default='off', max_length=8)),
                ('state_updated', models.DateTimeField(auto_now_add=True)),
                ('repeat', models.IntegerField(default=0)),
                ('repeat_count', models.IntegerField(default=1)),
                ('volume', models.IntegerField(default=100)),
                ('custom_sound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doorbell.Sound')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
